select *
from (
SELECT  op.NOME_PRODUTO  
	     ,SUM(if(op.TIPO_OPERACAO ='C', OP.QUANTIDADE, -1 * OP.QUANTIDADE)) QUANTIDADE 
	     ,ROUND( SUM(  if(op.TIPO_OPERACAO ='C', OP.VR_UNITARIO,-1*OP.VR_UNITARIO)) / (SELECT COUNT(1) 
	        FROM TB_OPERACAO OP2 
	        WHERE OP2.NOME_PRODUTO = OP.NOME_PRODUTO 
	           AND OP2.TIPO_OPERACAO = OP.TIPO_OPERACAO),2) CUSTO_MEDIO 
	    ,ROUND(SUM(if(op.TIPO_OPERACAO ='C',OP.QUANTIDADE,-1*OP.QUANTIDADE)) * ROUND( SUM(OP.VR_UNITARIO) / (SELECT COUNT(1) 
	        FROM TB_OPERACAO OP2 
	        WHERE OP2.NOME_PRODUTO = OP.NOME_PRODUTO 
	           AND OP2.TIPO_OPERACAO = OP.TIPO_OPERACAO),2),2) CUSTO_TOTAL 

        ,CA.NRO_CARTEIRA 
        ,CA.NOME AS NOME_CARTEIRA 
        ,PRD.SIGLA AS SIGLA
	FROM TB_OPERACAO OP 
	  INNER JOIN TB_CARTEIRA CA ON CA.NRO_CARTEIRA = OP.NRO_CARTEIRA 
     INNER JOIN tb_tipo_produto PRD ON PRD.NRO_TIPO_PRODUTO = OP.NRO_TIPO_PRODUTO 
	WHERE CA.NRO_CARTEIRA in (?) 
         AND CA.NRO_USUARIO = ? 
         and OP.DATA_OPERACAO <= ?
	GROUP BY op.NOME_PRODUTO  
             ,OP.NRO_TIPO_PRODUTO 
	) operacao
    where operacao.quantidade > 0
    order by operacao.SIGLA, NOME_PRODUTO
            